### ISSUE TITLE
ReCaptcha..

### ISSUE THREAD

**Issue by Pocker88** [noCaptchaAi/chrome-extension#4]
Didn't work extension and script for me..
Didnt solve.. open window with pictures and then simply stuck.

**Comment by 404b** [comment]
> Didn't work extension and script for me.. Didnt solve.. open window with pictures and then simply stuck.

Have you set up apikey?

**Comment by Pocker88** [comment]
Yes but still nothing... Any solve

**Comment by 404b** [comment]
> Yes but still nothing... Any solve

Use this update https://github.com/noCaptchaAi/chrome-extension/releases/tag/v1.7.6

**Comment by Pocker88** [comment]
Now this same have Bugs..

**Comment by 404b** [comment]
> No.. this same have Bugs..

Closed. issues without any details

**Comment by Tushar49** [comment]
Hey, I am facing similar issues with the latest 1.7.6 version of this extension. The reCaptcha opens but doesn't solve.

**Comment by 404b** [comment]
> No.. this same have Bugs..

There was an issue with free server, fixed now.
