### ISSUE TITLE
Extension not working for ReCaptchas

### ISSUE THREAD

**Issue by Tushar49** [noCaptchaAi/chrome-extension#7]
With regard to the issue https://github.com/noCaptchaAi/chrome-extension/issues/5 that was closed without any resolution and untimely, I am raising this new issue with request to not close it until the issue is actually resolved.
Also, yes the api key is setup as you can see below:
![image](https://user-images.githubusercontent.com/76201310/235891904-49871b1b-f2a5-4b11-b9a7-2a1fbdfee82a.png)

**Comment by 404b** [comment]
There was an issue with free server, fixed now.
