### ISSUE TITLE
Failed to fetch error

### ISSUE THREAD

**Issue by Testic19** [noCaptchaAi/chrome-extension#8]
![image](https://github.com/noCaptchaAi/chrome-extension/assets/76889671/f1fbea54-c026-4c2d-93fe-85d150652f12)
I added extension into selenium browser and it says failed to fetch when it tries to solve captcha

**Comment by Testic19** [comment]
![image](https://github.com/noCaptchaAi/chrome-extension/assets/76889671/fa2d9884-f2af-4c4b-87f7-7c7f1408b6da)

**Comment by 404b** [comment]
This will be addressed in next update, reconfig the extension when this happnes. Also you can hardcode it on background.js
